export const GET_SERVICE_LIST_SUCCESS = 'GET_SERVICE_LIST_SUCCESS'
export const GET_SERVICE_LIST_LOADING = 'GET_SERVICE_LIST_LOADING'
export const GET_SERVICE_LIST_FAILED = 'GET_SERVICE_LIST_FAILED'

export const GET_SERVICE_DETAIL_SUCCESS = 'GET_SERVICE_DETAIL_SUCCESS'
export const GET_SERVICE_DETAIL_LOADING = 'GET_SERVICE_DETAIL_LOADING'
export const GET_SERVICE_DETAIL_FAILED = 'GET_SERVICE_DETAIL_FAILED'

export const GET_SERVICE_MAPPING_SUCCESS = 'GET_SERVICE_MAPPING_SUCCESS'
export const GET_SERVICE_MAPPING_LOADING = 'GET_SERVICE_MAPPING_LOADING'
export const GET_SERVICE_MAPPING_FAILED = 'GET_SERVICE_MAPPING_FAILED'

export const ADD_SERVICE_MAPPING_SUCCESS = 'ADD_SERVICE_MAPPING_SUCCESS'
export const UPDATE_SERVICE_MAPPING_SUCCESS = 'UPDATE_SERVICE_MAPPING_SUCCESS'
export const UPDATE_SERVICE_MAPPING_LOADING = 'UPDATE_SERVICE_MAPPING_LOADING'
export const UPDATE_SERVICE_MAPPING_FAILED = 'UPDATE_SERVICE_MAPPING_FAILED'

export const UPDATE_SERVICE_DETAIL_SUCCESS = 'UPDATE_SERVICE_DETAIL_SUCCESS'
export const UPDATE_SERVICE_DETAIL_LOADING = 'UPDATE_SERVICE_DETAIL_LOADING'
export const UPDATE_SERVICE_DETAIL_FAILED = 'UPDATE_SERVICE_DETAIL_FAILED'

export const ADD_SERVICE_PROPERTY_SUCCESS = 'ADD_SERVICE_PROPERTY_SUCCESS'
export const DELETE_SERVICE_PROPERTY_SUCCESS = 'DELETE_SERVICE_PROPERTY_SUCCESS'
export const EDIT_SERVICE_PROPERTY_SUCCESS = 'EDIT_SERVICE_PROPERTY_SUCCESS'

export const UNMARK_SERVICE_PROPERTY_SUCCESS = 'EDIT_SERVICE_PROPERTY_SUCCESS'

export const IMPORT_PROPERTIES_SUCCESS = 'IMPORT_PROPERTIES_SUCCESS'

export const SERVICE_DETAIL_INIT = 'SERVICE_DETAIL_INIT'
export const APP_INIT_COMPLETE = 'APP_INIT_COMPLETE'

export const CHANGE_NAVIGATION = 'CHANGE_NAVIGATION'

export const GET_VERSION_LIST_SUCCESS = 'GET_VERSION_LIST_SUCCESS'
export const GET_VERSION_LIST_LOADING = 'GET_VERSION_LIST_LOADING'
export const GET_VERSION_LIST_FAILED = 'GET_VERSION_LIST_FAILED'

export const ADD_GLOBAL_ERROR = 'ADD_GLOBAL_ERROR'
export const REMOVE_GLOBAL_ERROR = 'REMOVE_GLOBAL_ERROR'
