const ACTION_TYPES = {
	ADD: 'ADD',
	DELETE: 'DELETE',
	EDIT: 'EDIT',
	CLONE: 'CLONE',
	NEW_VERSION: 'NEW_VERSION'
}

const APP_CONFIG = {
	PAGING: {
		PAGE_NUMBER: 1,
		PAGE_SIZE: 20
	},
	PROPERTY_GROUPS: {
		REQUEST: 'request',
		RESPONSE: 'response',
		HEADER: 'header',
		ROUTE: 'route'
	},
	PROPERTY_CHANGE_TYPES: {
		NEW: 'NEW',
		UPDATE: 'UPDATE',
		DELETE: 'DELETE'
	},
	GROUP_ACTIONS: {
		ADD: 'ADD',
		DELETE: 'DELETE',
		EDIT: 'EDIT',
		CLONE: 'CLONE'
	},
	SERVICE_TYPES: {
		REST: 'REST',
		SOAP: 'SOAP'
	},
	ACTION_TYPES: ACTION_TYPES,
	PROPERTY_TYPES: [
		'date',
		'dateTime',
		'time',
		'string',
		'decimal',
		'long',
		'boolean',
		'int',
		'positiveInteger',
		'object',
		'array'
	],
	SERVICE_LIST_ACTIONS: {
		SERVICES_GROUP_CONTAINER_ACTIONS: [ACTION_TYPES.ADD],
		SERVICES_ITEM_ACTIONS: [ACTION_TYPES.NEW_VERSION, ACTION_TYPES.EDIT]
	},
	SERVICE_DETAIL_ACTIONS: {
		PROPERTIES_GROUP_CONTAINER_ACTIONS: [ACTION_TYPES.ADD],
		PROPERTIES_GROUP_ACTIONS: [
			ACTION_TYPES.ADD,
			ACTION_TYPES.CLONE,
			ACTION_TYPES.DELETE,
			ACTION_TYPES.EDIT
		],
		PROPERTIES_ITEMS_ACTIONS: [ACTION_TYPES.DELETE, ACTION_TYPES.EDIT],
		USE_CASE_LIST_GROUP_ACTIONS: [ACTION_TYPES.ADD, ACTION_TYPES.CLONE],
		USE_CASE_SERVICES_ITEM_ACTIONS: [ACTION_TYPES.ADD],
		MAPPING_PROPERTY_LIST_ITEMS_ACTIONS: [ACTION_TYPES.EDIT]
	},
	IMPORT_LIST_ACTIONS: {
		IMPORT_LIST_GROUP_CONTAINER_ACTIONS: [ACTION_TYPES.ADD]
	},
	IMPORT_DETAIL_ACTIONS: {
		IMPORT_DETAIL_PROPERTY_GROUP_CONTAINER_ACTIONS: [ACTION_TYPES.ADD]
	},
	MODAL_WINDOW_STYLES: {
		content: {
			top: '50%',
			left: '50%',
			right: 'auto',
			bottom: 'auto',
			marginRight: '-50%',
			transform: 'translate(-50%, -50%)',
			minWidth: '300px',
			padding: '10px 15px 10px 15px'
		}
	}
}

export default APP_CONFIG
